[[ProtocolBuffersLite]]
arch = "aarch64"
git-tree-sha1 = "b5c6558bfa1cef332d4ffacae0de17f1731d1e6f"
os = "macos"

    [[ProtocolBuffersLite.download]]
    sha256 = "5536baaa1507290596ded067b1fe9a6653602b3a4b0306d70e2a6acf68962a4e"
    url = "https://github.com/JuliaBinaryWrappers/ProtocolBuffersLite_jll.jl/releases/download/ProtocolBuffersLite-v3.16.1+0/ProtocolBuffersLite.v3.16.1.aarch64-apple-darwin.tar.gz"
[[ProtocolBuffersLite]]
arch = "aarch64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "35d9415727477251b8fe1f8f03385a94a0a9b8aa"
libc = "glibc"
os = "linux"

    [[ProtocolBuffersLite.download]]
    sha256 = "5d81e4bb8ea867ae8b02c4505adc6e4dc772db869cb810fa02753db2ea052ae0"
    url = "https://github.com/JuliaBinaryWrappers/ProtocolBuffersLite_jll.jl/releases/download/ProtocolBuffersLite-v3.16.1+0/ProtocolBuffersLite.v3.16.1.aarch64-linux-gnu-cxx11.tar.gz"
[[ProtocolBuffersLite]]
arch = "aarch64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "d70c0b9d8e8b2017d39d994a5e88effe114b74a7"
libc = "musl"
os = "linux"

    [[ProtocolBuffersLite.download]]
    sha256 = "12c70747ec127a5c969600c74b7625bd6de0d2b0dbc9a396e7469b98d0375c7c"
    url = "https://github.com/JuliaBinaryWrappers/ProtocolBuffersLite_jll.jl/releases/download/ProtocolBuffersLite-v3.16.1+0/ProtocolBuffersLite.v3.16.1.aarch64-linux-musl-cxx11.tar.gz"
[[ProtocolBuffersLite]]
arch = "aarch64"
git-tree-sha1 = "78476f14f7a68b28973eccb043eb395288aa6124"
os = "freebsd"

    [[ProtocolBuffersLite.download]]
    sha256 = "b59c3f9947d1dcaeb245b17660cf548894672176f257feb9d2b127a9f8b37a78"
    url = "https://github.com/JuliaBinaryWrappers/ProtocolBuffersLite_jll.jl/releases/download/ProtocolBuffersLite-v3.16.1+0/ProtocolBuffersLite.v3.16.1.aarch64-unknown-freebsd.tar.gz"
[[ProtocolBuffersLite]]
arch = "armv6l"
call_abi = "eabihf"
cxxstring_abi = "cxx11"
git-tree-sha1 = "c957182b6d3c19e9be903f2dff8fc9c9d6ffba14"
libc = "glibc"
os = "linux"

    [[ProtocolBuffersLite.download]]
    sha256 = "aaf53ffe2430f674ae32db4b69a9b609ebe23a492a0b312458a82c9327a1eabd"
    url = "https://github.com/JuliaBinaryWrappers/ProtocolBuffersLite_jll.jl/releases/download/ProtocolBuffersLite-v3.16.1+0/ProtocolBuffersLite.v3.16.1.armv6l-linux-gnueabihf-cxx11.tar.gz"
[[ProtocolBuffersLite]]
arch = "armv6l"
call_abi = "eabihf"
cxxstring_abi = "cxx11"
git-tree-sha1 = "e182bb47daec4a669a54020f696df52e527e0d11"
libc = "musl"
os = "linux"

    [[ProtocolBuffersLite.download]]
    sha256 = "fdb03748357a77e97990ec65041cf096fff8f2a1ea4320d0f37e3b172c82eda8"
    url = "https://github.com/JuliaBinaryWrappers/ProtocolBuffersLite_jll.jl/releases/download/ProtocolBuffersLite-v3.16.1+0/ProtocolBuffersLite.v3.16.1.armv6l-linux-musleabihf-cxx11.tar.gz"
[[ProtocolBuffersLite]]
arch = "armv7l"
call_abi = "eabihf"
cxxstring_abi = "cxx11"
git-tree-sha1 = "a801cd069a95e7b9eab9fc3e9d94bc8d5d7434e8"
libc = "glibc"
os = "linux"

    [[ProtocolBuffersLite.download]]
    sha256 = "e460a83d9f0c752df5acb6bb6923fa727a22fa62f69684834f6a9ccaa4d538f4"
    url = "https://github.com/JuliaBinaryWrappers/ProtocolBuffersLite_jll.jl/releases/download/ProtocolBuffersLite-v3.16.1+0/ProtocolBuffersLite.v3.16.1.armv7l-linux-gnueabihf-cxx11.tar.gz"
[[ProtocolBuffersLite]]
arch = "armv7l"
call_abi = "eabihf"
cxxstring_abi = "cxx11"
git-tree-sha1 = "b28618f565758bb1da28aca9250c6b02182dadd1"
libc = "musl"
os = "linux"

    [[ProtocolBuffersLite.download]]
    sha256 = "99ba53df72369cad0a0d82fa3d0fd5dd13f3ff80c32e00237f7ad65df1a52cb7"
    url = "https://github.com/JuliaBinaryWrappers/ProtocolBuffersLite_jll.jl/releases/download/ProtocolBuffersLite-v3.16.1+0/ProtocolBuffersLite.v3.16.1.armv7l-linux-musleabihf-cxx11.tar.gz"
[[ProtocolBuffersLite]]
arch = "i686"
cxxstring_abi = "cxx11"
git-tree-sha1 = "3f4dba6b657d9346f2509a0e39b451992983ad54"
libc = "glibc"
os = "linux"

    [[ProtocolBuffersLite.download]]
    sha256 = "8e375dfdaeeaf588faa89c906831902ea67f9eddbcd136e747a81b4c25b46659"
    url = "https://github.com/JuliaBinaryWrappers/ProtocolBuffersLite_jll.jl/releases/download/ProtocolBuffersLite-v3.16.1+0/ProtocolBuffersLite.v3.16.1.i686-linux-gnu-cxx11.tar.gz"
[[ProtocolBuffersLite]]
arch = "i686"
cxxstring_abi = "cxx11"
git-tree-sha1 = "6cc08617b8e40567335aeaa8d6ea803f010aab12"
libc = "musl"
os = "linux"

    [[ProtocolBuffersLite.download]]
    sha256 = "6f0f9b0f474ff26a1c279c25c29ec3ce4e93cedb4a36b3b72da3d055b58366cd"
    url = "https://github.com/JuliaBinaryWrappers/ProtocolBuffersLite_jll.jl/releases/download/ProtocolBuffersLite-v3.16.1+0/ProtocolBuffersLite.v3.16.1.i686-linux-musl-cxx11.tar.gz"
[[ProtocolBuffersLite]]
arch = "i686"
cxxstring_abi = "cxx11"
git-tree-sha1 = "bf9b9a7f61e2cdb1bacc8e9832cb3d6c435d820c"
os = "windows"

    [[ProtocolBuffersLite.download]]
    sha256 = "bed03f5c950082b6ba1f6beb46fd96f39bcc6362ae754e907db6edd9d0017865"
    url = "https://github.com/JuliaBinaryWrappers/ProtocolBuffersLite_jll.jl/releases/download/ProtocolBuffersLite-v3.16.1+0/ProtocolBuffersLite.v3.16.1.i686-w64-mingw32-cxx11.tar.gz"
[[ProtocolBuffersLite]]
arch = "powerpc64le"
cxxstring_abi = "cxx11"
git-tree-sha1 = "39135936363daccb035e2fd8006659a3619d30aa"
libc = "glibc"
os = "linux"

    [[ProtocolBuffersLite.download]]
    sha256 = "3f21c9cf45c096ccb33e5e17a180b0a1b6d0c87a1ad223ceedfe55e283f9aeb5"
    url = "https://github.com/JuliaBinaryWrappers/ProtocolBuffersLite_jll.jl/releases/download/ProtocolBuffersLite-v3.16.1+0/ProtocolBuffersLite.v3.16.1.powerpc64le-linux-gnu-cxx11.tar.gz"
[[ProtocolBuffersLite]]
arch = "riscv64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "98e85b948661d5da36ba30bc892c6eba53d5f109"
libc = "glibc"
os = "linux"

    [[ProtocolBuffersLite.download]]
    sha256 = "a8ca26e11410ff579290680ddde697ac537d48644bec2e429951f55d9ef48c8f"
    url = "https://github.com/JuliaBinaryWrappers/ProtocolBuffersLite_jll.jl/releases/download/ProtocolBuffersLite-v3.16.1+0/ProtocolBuffersLite.v3.16.1.riscv64-linux-gnu-cxx11.tar.gz"
[[ProtocolBuffersLite]]
arch = "x86_64"
git-tree-sha1 = "7a67f8eb04bd27db5a1269d8ffbac783516f4764"
os = "macos"

    [[ProtocolBuffersLite.download]]
    sha256 = "cd7582345e998a3c841a66834b89932c598c6a361d77cc39f5790534c2c084b6"
    url = "https://github.com/JuliaBinaryWrappers/ProtocolBuffersLite_jll.jl/releases/download/ProtocolBuffersLite-v3.16.1+0/ProtocolBuffersLite.v3.16.1.x86_64-apple-darwin.tar.gz"
[[ProtocolBuffersLite]]
arch = "x86_64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "ac183469c715250bfcad800b5a12912570a78cdf"
libc = "glibc"
os = "linux"

    [[ProtocolBuffersLite.download]]
    sha256 = "27d648e14736881a63380329bba0f0c1deffbcf30c557fbb8de5dd8699df20e0"
    url = "https://github.com/JuliaBinaryWrappers/ProtocolBuffersLite_jll.jl/releases/download/ProtocolBuffersLite-v3.16.1+0/ProtocolBuffersLite.v3.16.1.x86_64-linux-gnu-cxx11.tar.gz"
[[ProtocolBuffersLite]]
arch = "x86_64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "f8630f66e1936bc9ae14f4bfe147ba7c0c1add93"
libc = "musl"
os = "linux"

    [[ProtocolBuffersLite.download]]
    sha256 = "42ba8e279602aaf1059f21555f4dc55b1a5133f3241ee31869676b2539318eb6"
    url = "https://github.com/JuliaBinaryWrappers/ProtocolBuffersLite_jll.jl/releases/download/ProtocolBuffersLite-v3.16.1+0/ProtocolBuffersLite.v3.16.1.x86_64-linux-musl-cxx11.tar.gz"
[[ProtocolBuffersLite]]
arch = "x86_64"
git-tree-sha1 = "a7c7352575181095b4bee1ba51adde79bd960e09"
os = "freebsd"

    [[ProtocolBuffersLite.download]]
    sha256 = "41e1dcb2fdc2b2fc68f2aaed01b735e8044feb8ef556ac35a3b46f37cf9ff0cd"
    url = "https://github.com/JuliaBinaryWrappers/ProtocolBuffersLite_jll.jl/releases/download/ProtocolBuffersLite-v3.16.1+0/ProtocolBuffersLite.v3.16.1.x86_64-unknown-freebsd.tar.gz"
[[ProtocolBuffersLite]]
arch = "x86_64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "5eb3d218c2abbf5c89a3cd1a63027d7980ca6b4c"
os = "windows"

    [[ProtocolBuffersLite.download]]
    sha256 = "9c1a55c36dddd603d6e460f335c8a1fd16ec519aeb00e220e040aef4704b2aa3"
    url = "https://github.com/JuliaBinaryWrappers/ProtocolBuffersLite_jll.jl/releases/download/ProtocolBuffersLite-v3.16.1+0/ProtocolBuffersLite.v3.16.1.x86_64-w64-mingw32-cxx11.tar.gz"
